{% set name = "GooseMPL" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e5898674eed179d2a4175b0408ccb018f490766042359dd92406ac847a1e87d1

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - deprecation
    - matplotlib-base
    - numpy
    - python >=3
    - scipy

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tdegeus/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple wrapper around pyplot.
  description: A simple wrapper around pyplot.
  doc_url: https://github.com/tdegeus/{{ name }}
  dev_url: https://github.com/tdegeus/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
