{% set name = "goosempl" %}
{% set version = "0.4.0" %}
{% set sha256 = "712ad9a2d30233cc47b3dfdf5ec0bd41a357222d3721583df6bc350c61dd525b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseMPL/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - matplotlib-base

test:
  imports:
    - GooseMPL

about:
  home: https://github.com/tdegeus/GooseMPL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple wrapper around pyplot.
  description: A simple wrapper around pyplot.
  doc_url: https://github.com/tdegeus/GooseMPL
  dev_url: https://github.com/tdegeus/GooseMPL

extra:
  recipe-maintainers:
    - tdegeus
